# Generated by Django 5.0.6 on 2024-06-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
                ('postal_street', models.CharField(max_length=255)),
                ('postal_suburb', models.CharField(max_length=255)),
                ('postal_state', models.CharField(max_length=255)),
                ('postal_postcode', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(max_length=20)),
                ('education_region', models.CharField(max_length=255)),
                ('broad_classification', models.CharField(max_length=255)),
                ('classification_group', models.CharField(max_length=255)),
                ('low_year', models.IntegerField()),
                ('high_year', models.IntegerField()),
                ('total_students', models.IntegerField()),
                ('be_score', models.FloatField()),
                ('icsea', models.FloatField()),
                ('atar_rank', models.FloatField()),
                ('median_atar', models.FloatField()),
                ('percent_students_with_atar', models.FloatField()),
            ],
        ),
    ]
